### ISSUE TITLE
Meeting 1

### ISSUE THREAD

**Issue by BruhatMusunuru** [UBC-MDS/prepropy#1]
In the first meeting, we discussed and decided on creating  a python package to streamline the pre-processing for machine learning pipelines.
Tasks to Complete:
- [x] Get TA's approval on the topic (Pan)
- [x] Conformation on if we should fork or can just use a branch
- [x] Setup repo structure (Jason)
- [x] Creating git repo and setting up documentation (Bruhat)

Functions Planned:

- [x] Scaling (Bruhat)
- [x] Imputation (Jason)
- [x] EDA (Pan)

Next Scheduled meeting 27th Feb, 9 PM Beijing time.

**Comment by jachang0628** [comment]
done

**Comment by jachang0628** [comment]
done
